# 本文件用于已部署好的系统检测自己是否需要升级使用，怕有人担心安全一类的问题，所以不提供服务器接口来做
lastVersion=1.1.4

upgradeContent=1. 优化文档展示细节，优化开放文档样式；\
2. SQL执行器数据量过大自动开启分页；\
3. SQL执行器页面优化，已知问题修复；\
4. 获取数据源连接配置优化，druid版本升级到1.2.16；\
5. 数据源支持MySQL8.x版本；\
6. #I6IUWC 解决vue变量赋值问题；\
7. #I6IWI9 解决没有升级脚本时提示没有找到文件问题；

upgradeUrl=https://gitee.com/zyplayer/zyplayer-doc/releases
nextStep=

