# 本文件用于已部署好的系统检测自己是否需要升级使用，怕有人担心安全一类的问题，所以不提供服务器接口来做
lastVersion=1.1.2

upgradeContent=1. #I636K1 全局搜索优化；\
2. 同步闭源版本部分代码，修复页面顺序问题；\
3. 添加注释和使用lombok @Mdai；\
4. 修复初始化显示文档菜单显示高亮问题，修复重复点击报错问题 @〝走走停停；\
5. 使用 @RequiredArgsConstructor 进行注入 @handy；\
6. md预览过滤格式，tree图标，打包版本指定 @护身法；\
7. mysql->oracle建表语句转换 @diantu；\
8. sqlserver->mysql建表语句转换 @diantu；\
9. 自动执行升级SQL、历史记录改为数据库存储、去掉git操作，优化代码结构，去掉不需要的文件；\
10. 将wiki升级为vue3版本；\
11. #I69PMN 修复模态框点击关闭问题；\
12. WIKI空间支持分页，页面展示优化；\
13. #I69ZVX 修改不能保存表情问题，优化脚本；\
14. 修复mysql数据库使用前置sql语句时,因数据库名包含特殊字符导致的报错问题 @diantu；\
15. 修复oracle使用use语句导致的报错问题 @diantu；\
16. 新增达梦数据库支持 @diantu；\

upgradeUrl=https://gitee.com/zyplayer/zyplayer-doc/releases
nextStep=

